train:
  vocab_size: 10000
  input_length: 200
  embedding_dim: 100
  learning_rate: 0.001
  validation_split: 0.2
  epochs: 100
  batch_size: 64
  lstm_01_units: 100
  lstm_02_units: 50
  dense_01_units: 50
  dense_02_units: 50
  hidden_activation: "tanh"
  regularization_factor: 0.001
  dropout_factor: 0.2
