prepare:
  remove_stopwords: 1
  remove_shadda: 1
  remove_tashkeel: 1
  remove_tatweel: 1
  remove_punc: 1
  normalize: 1
  remove_repeats: 1
  remove_nonarabic: 1
  stemming: 0
train:
  vocab_size: 10000
  input_length: 200
  embedding_dim: 100
  learning_rate: 0.0003
  validation_split: 0.2
  epochs: 100
  batch_size: 32
  cnn_units: [32]
  cnn_kernels: [3]
  dense_units: [32, 32]
  hidden_activation: "relu"
  regularization_factor: 0.001
  dropout_factor: 0.2
