prepare:
  remove_stopwords: 1
  remove_shadda: 1
  remove_tashkeel: 1
  remove_tatweel: 1
  remove_punc: 1
  normalize: 1
  remove_repeats: 1
  remove_nonarabic: 1
  stemming: 1
train:
  vocab_size: 10000
  input_length: 200
  embedding_dim: 100
  learning_rate: 0.0001
  validation_split: 0.2
  epochs: 64
  batch_size: 50
  cnn_units: [256]
  cnn_kernels: [3]
  dense_units: [128]
  hidden_activation: "relu"
  regularization_factor: 0.001
  dropout_factor: 0
